import React, { useRef, useState, useEffect } from 'react';
import { useApp } from '../contexts/AppContext';
import { IdentityCard } from './IdentityCardGenerator';
import { supabase, IdentityCard as IdentityCardType } from '../lib/supabase';

const CARD_COLORS = ['blue', 'green', 'purple', 'red', 'orange', 'teal', 'gold', 'indigo', 'pink', 'rose', 'cyan', 'slate'] as const;
const CARD_DESIGNS = ['modern', 'classic', 'minimal', 'premium', 'corporate', 'sport'] as const;
const FONT_OPTIONS = ['sans', 'serif', 'rounded'] as const;
const BORDER_OPTIONS = ['rounded', 'square', 'soft'] as const;
const COLOR_THEMES: Record<string, { primary: string }> = {
  blue: { primary: '#1e40af' }, green: { primary: '#166534' }, purple: { primary: '#6b21a8' },
  red: { primary: '#991b1b' }, orange: { primary: '#9a3412' }, teal: { primary: '#0f766e' },
  gold: { primary: '#92400e' }, indigo: { primary: '#3730a3' }, pink: { primary: '#9d174d' },
  rose: { primary: '#9f1239' }, cyan: { primary: '#0e7490' }, slate: { primary: '#334155' },
};

export function StudentIdentityCardView() {
  const { currentUser } = useApp();
  const cardRef = useRef<HTMLDivElement>(null);
  const [color, setColor] = useState('blue');
  const [design, setDesign] = useState('modern');
  const [fontStyle, setFontStyle] = useState('sans');
  const [borderStyle, setBorderStyle] = useState('rounded');
  const [savedCard, setSavedCard] = useState<IdentityCardType | null>(null);
  const [loading, setLoading] = useState(true);

  const student = currentUser?.student;
  const userId = currentUser?.user.id;

  useEffect(() => {
    if (!userId) { setLoading(false); return; }
    const fetchCard = async () => {
      const { data } = await supabase.from('identity_cards').select('*').eq('user_id', userId).single();
      if (data) {
        setSavedCard(data);
        setColor(data.color_theme);
        setDesign(data.design_type);
        const cd = data.card_data as any;
        if (cd.fontStyle) setFontStyle(cd.fontStyle);
        if (cd.borderStyle) setBorderStyle(cd.borderStyle);
      }
      setLoading(false);
    };
    fetchCard();
  }, [userId]);

  const cardData = savedCard?.card_data ? {
    fullName: (savedCard.card_data as any).fullName || currentUser?.user.full_name || '',
    rollNumber: (savedCard.card_data as any).rollNumber || student?.roll_number || '',
    className: (savedCard.card_data as any).className || student?.class?.name || '',
    section: (savedCard.card_data as any).section || student?.class?.section || '',
    guardianName: (savedCard.card_data as any).guardianName || student?.guardian_name || '',
    guardianPhone: (savedCard.card_data as any).guardianPhone || student?.guardian_phone || '',
    address: (savedCard.card_data as any).address || student?.address || '',
    admissionDate: (savedCard.card_data as any).admissionDate || student?.admission_date || '',
    bloodGroup: (savedCard.card_data as any).bloodGroup || '',
  } : null;

  const autoCardData = student ? {
    fullName: currentUser!.user.full_name, rollNumber: student.roll_number,
    className: student.class?.name || '', section: student.class?.section || '',
    guardianName: student.guardian_name, guardianPhone: student.guardian_phone,
    address: student.address || '', admissionDate: student.admission_date,
  } : null;

  const displayData = cardData || autoCardData;

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow || !cardRef.current) return;
    printWindow.document.write(`<html><head><title>Identity Card - ${displayData?.fullName || ''}</title><style>body{display:flex;justify-content:center;align-items:center;min-height:100vh;margin:0}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}</style></head><body>${cardRef.current.innerHTML}</body></html>`);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => printWindow.print(), 500);
  };

  if (loading) return <div className="flex items-center justify-center py-12"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600" /></div>;
  if (!displayData) return <div className="text-center py-12 text-neutral-400">No student data available.</div>;

  return (
    <div className="space-y-6">
      <h2 className="text-xl font-bold text-neutral-900">My Identity Card{savedCard && <span className="ml-2 text-sm font-normal text-success-600">(Generated by Admin)</span>}</h2>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="space-y-4">
          <div className="bg-white border border-neutral-200 rounded-xl p-6 space-y-5">
            <div>
              <h3 className="font-semibold text-neutral-900 mb-3">Color Theme</h3>
              <div className="flex flex-wrap gap-2">
                {CARD_COLORS.map((c) => (
                  <button key={c} onClick={() => setColor(c)}
                    className={`w-8 h-8 rounded-full border-2 transition-all ${color === c ? 'border-neutral-900 scale-110 ring-2 ring-offset-1 ring-neutral-900' : 'border-transparent hover:scale-105'}`}
                    style={{ background: COLOR_THEMES[c].primary }} title={c} />
                ))}
              </div>
            </div>
            <div>
              <h3 className="font-semibold text-neutral-900 mb-3">Design</h3>
              <div className="grid grid-cols-3 gap-2">
                {CARD_DESIGNS.map((d) => (
                  <button key={d} onClick={() => setDesign(d)}
                    className={`px-3 py-2 rounded-lg text-sm font-medium transition-all capitalize ${design === d ? 'bg-primary-600 text-white shadow-md' : 'bg-neutral-100 text-neutral-600 hover:bg-neutral-200 border border-neutral-200'}`}>
                    {d}
                  </button>
                ))}
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <h3 className="font-semibold text-neutral-900 mb-2 text-sm">Font</h3>
                <div className="flex gap-1.5">
                  {FONT_OPTIONS.map((f) => (
                    <button key={f} onClick={() => setFontStyle(f)}
                      className={`flex-1 px-2 py-2 rounded-lg text-xs font-medium transition-all capitalize ${fontStyle === f ? 'bg-primary-600 text-white' : 'bg-neutral-100 text-neutral-600 hover:bg-neutral-200'}`}>
                      {f}
                    </button>
                  ))}
                </div>
              </div>
              <div>
                <h3 className="font-semibold text-neutral-900 mb-2 text-sm">Border</h3>
                <div className="flex gap-1.5">
                  {BORDER_OPTIONS.map((b) => (
                    <button key={b} onClick={() => setBorderStyle(b)}
                      className={`flex-1 px-2 py-2 rounded-lg text-xs font-medium transition-all capitalize ${borderStyle === b ? 'bg-primary-600 text-white' : 'bg-neutral-100 text-neutral-600 hover:bg-neutral-200'}`}>
                      {b}
                    </button>
                  ))}
                </div>
              </div>
            </div>
            {savedCard && <p className="text-xs text-neutral-500 text-center">This card was issued by the administration. Customize color/design/font/border for print.</p>}
          </div>
          <button onClick={handlePrint} className="w-full px-4 py-2.5 bg-neutral-800 text-white rounded-xl font-medium hover:bg-neutral-900 transition-colors">🖨 Print Identity Card</button>
        </div>
        <div className="flex flex-col items-center justify-start">
          <div ref={cardRef}>
            <IdentityCard data={displayData} color={color} design={design} fontStyle={fontStyle} borderStyle={borderStyle} />
          </div>
        </div>
      </div>
    </div>
  );
}
