-- Identity cards generated by admin for students and teachers
CREATE TABLE identity_cards (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  card_type TEXT NOT NULL CHECK (card_type IN ('student', 'teacher')),
  card_data JSONB NOT NULL,
  color_theme TEXT NOT NULL DEFAULT 'blue',
  design_type TEXT NOT NULL DEFAULT 'modern',
  generated_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id)
);

CREATE INDEX idx_identity_cards_user ON identity_cards(user_id);
CREATE INDEX idx_identity_cards_type ON identity_cards(card_type);
